baseURL = "https://grabowski74.github.io/matheuspet/"
languageCode = "en-us"
publishDir = "docs"
title = "Matheus"
theme = "minimal-master"
disqusShortname = "grabowski74" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Matheus Silva Araújo"
    description = "Seleção do PET-Computação"
    githubUsername = "#"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Missões"
    weight = 2

[[menu.main]]
    url = "/about/about"
    name = "Sobre"
    weight = 3

[[menu.main]]
    url = "http://www.dsc.ufcg.edu.br/~pet/"
    name = "PET"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:matheus.araujo@ccc.ufcg.edu.br"
    name = "google"
    weight = 8

[[menu.icon]]
    url = "https://github.com/grabowski74/"
    name = "github"
    weight = 7

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "twitter"
    weight = 6

[[menu.icon]]
    url = "https://www.youtube.com/channel/UCmO6IflVC626XI790VSO7MA?view_as=subscriber"
    name = "youtube"
    weight = 5

[[menu.icon]]
    url = "https://www.facebook.com/matheusa4/"
    name = "facebook"
    weight = 4

 [[menu.icon]]
    url = "https://www.instagram.com/th1araujo/"
    name = "instagram"
    weight = 3

[[menu.icon]]
    url = "https://open.spotify.com/user/12142437138"
    name = "spotify"
    weight = 2

[[menu.icon]]
    url = "https://www.last.fm/user/th1araujo"
    name = "lastfm"
    weight = 1
